/* eslint-disable @typescript-eslint/no-unused-vars */
"use client";
import React, {
  createContext,
  useState,
  useContext,
  useEffect,
  useCallback,
} from "react";
import { useAuth } from "./AuthContext";

import { v4 as uuidv4 } from "uuid";
import { httpClient } from "@/src/data/api/httpClient";
import { parseAllNumbers } from "@/src/utils";
import { toast } from "@/components/ui/use-toast";
import {
  WeldingContextType,
  WeldingJob,
  WeldingJobStatus,
} from "@/src/types/welding";
import {
  WeldingMaterialNeeded,
  WeldingMaterialStock,
} from "@/src/types/weldingMaterial";

const WeldingContext = createContext<WeldingContextType | undefined>(undefined);

const WELDING_JOBS_STORAGE_KEY = "@SimuPOS_WeldingJobs";
const WELDING_MATERIAL_STOCK_STORAGE_KEY = "@SimuPOS_WeldingMaterialStock";

export const WeldingProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const { user, currentBranchId, getAuthHeaders } = useAuth();
  const [weldingJobs, setWeldingJobs] = useState<WeldingJob[]>([]);
  const [materialStock, setMaterialStock] = useState<WeldingMaterialStock[]>(
    []
  );
  const [loadingJobs, setLoadingJobs] = useState<boolean>(true);
  const [loadingMaterialStock, setLoadingMaterialStock] =
    useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [errorMaterialStock, setErrorMaterialStock] = useState<string | null>(
    null
  );
  const [isSyncing, setIsSyncing] = useState<boolean>(false);
  const [lastSyncTime, setLastSyncTime] = useState<Date | null>(null);
  const [totalJobs, setTotalJobs] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const branchId = currentBranchId;

  const fetchWeldingJobs = useCallback(
    async (page = 1, limit = 10, status = "all") => {
      if (!branchId) return;
      setLoadingJobs(true);
      setError(null);
      try {
        const headers = await getAuthHeaders();
        const params = new URLSearchParams({
          page: page.toString(),
          limit: limit.toString(),
        });
        if (status !== "all") {
          params.append("status", status);
        }
        const response = await httpClient(
          `/welding/jobs/branch/${branchId}?${params.toString()}`,
          {
            headers,
          }
        );

        if (response?.jobs) {
          const parsedJobs = parseAllNumbers(response.jobs);
          setWeldingJobs(parsedJobs);
          setTotalJobs(response.totalJobs || 0);
          setCurrentPage(response.currentPage || 1);
          setTotalPages(response.totalPages || 1);
          setLastSyncTime(new Date());
        }
      } catch (err) {
        console.error("Failed to fetch welding jobs from backend:", err);
        setError("Failed to fetch jobs from server.");
      } finally {
        setLoadingJobs(false);
      }
    },
    [branchId, getAuthHeaders]
  );

  const fetchMaterialStock = useCallback(async () => {
    if (!branchId) return;
    setLoadingMaterialStock(true);
    setErrorMaterialStock(null);
    try {
      const headers = await getAuthHeaders();
      const response = await httpClient(
        `/welding/stock/materials/branch/${branchId}`,
        { headers }
      );
      if (response?.stockItems) {
        setMaterialStock(parseAllNumbers(response.stockItems));
      }
    } catch (err) {
      console.error("Failed to fetch material stock from backend:", err);
      setErrorMaterialStock("Failed to fetch stock from server.");
    } finally {
      setLoadingMaterialStock(false);
    }
  }, [branchId, getAuthHeaders]);

  useEffect(() => {
    if (branchId) {
      fetchWeldingJobs();
      fetchMaterialStock();
    }
  }, [branchId, fetchWeldingJobs, fetchMaterialStock]);

  const addWeldingJob = async (
    jobData: Omit<WeldingJob, "id" | "createdAt" | "updatedAt" | "status">
  ) => {
    if (!branchId) {
      toast({
        title: "Error",
        description: "Branch ID is required",
        variant: "destructive",
      });
      return null;
    }

    try {
      if (user && branchId) {
        const headers = await getAuthHeaders();
        // Clean job data by removing materialsNeeded as they are sent separately in the root payload
        // This avoids "materialsNeeded[0].weldingJobId is not allowed" validation errors on the backend
        const { materialsNeeded, ...restOfJobData } = jobData as any;

        // Clean materials to remove fields that should be generated by the backend
        const cleanedMaterials = (materialsNeeded || []).map((material: any) => {
          const { id, weldingJobId, createdAt, updatedAt, ...cleanMaterial } =
            material;
          return cleanMaterial;
        });

        const payload = {
          job: {
            ...restOfJobData,
            branchId: branchId,
          },
          materials: cleanedMaterials,
        };

        const response = await httpClient("/welding/jobs", {
          method: "POST",
          headers: {
            ...headers,
            "Content-Type": "application/json",
          },
          body: JSON.stringify(payload),
        });

        // Ensure we handle response structure correctly
        const createdJob = response?.job || response?.data?.job || response;

        if (!createdJob || !createdJob.id) {
          throw new Error("Invalid response from server");
        }

        const parsedJob = parseAllNumbers(createdJob);
        setWeldingJobs((prev) => [...prev, parsedJob]);
        fetchWeldingJobs(currentPage);
        return parsedJob;
      } else {
        // Offline fallback
        const newJob: WeldingJob = {
          ...jobData,
          id: uuidv4(),
          status: WeldingJobStatus.PENDING,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          branchId: branchId,
        };
        setWeldingJobs((prev) => [...prev, newJob]);
        return newJob;
      }
    } catch (err) {
      console.error("Failed to create job:", err);
      toast({
        title: "Error",
        description: err instanceof Error ? err.message : "Failed to create welding job",
        variant: "destructive",
      });
      // Do NOT return the optimistic job on actual error
      return null;
    }
  };

  // const addWeldingJob = async (
  //   jobData: Omit<WeldingJob, "id" | "createdAt" | "updatedAt" | "status">
  // ) => {
  //   if (!branchId) {
  //     toast({
  //       title: "Error",
  //       description: "Branch ID is required",
  //       variant: "destructive",
  //     });
  //     return null;
  //   }
  //   try {
  //     const headers = await getAuthHeaders();
  //     const payload = { ...jobData, branchId };
  //     console.log("Creating welding job with payload:", payload);
  //     const response = await httpClient("/welding/jobs", {
  //       method: "POST",
  //       headers,
  //       body: JSON.stringify(payload),
  //     });
  //     fetchWeldingJobs(currentPage);
  //     return response;
  //   } catch (err) {
  //     console.error("Failed to create job:", err);
  //     toast({
  //       title: "Error",
  //       description: "Failed to create welding job",
  //       variant: "destructive",
  //     });
  //     return null;
  //   }
  // };

  const updateWeldingJob = async (
    jobId: string,
    updates: Partial<WeldingJob>
  ) => {
    // Get current job first
    const currentJob = weldingJobs.find((job) => job.id === jobId);
    if (!currentJob) {
      toast({
        title: "Error",
        description: "Job not found",
        variant: "destructive",
      });
      return;
    }

    // Create update payload - exclude fields that shouldn't be updated
    const updatePayload = {
      ...updates,
      assignedArtisans: updates.assignedArtisans || [], // Ensure array format
    };

    // Remove fields that should never be updated via this endpoint
    delete updatePayload.id;
    delete updatePayload.branchId;
    delete updatePayload.createdAt;
    delete updatePayload.updatedAt;
    delete updatePayload.materialsNeeded;
    delete updatePayload.expenses;
    delete updatePayload.assignments;
    delete updatePayload.totalExpenses;
    delete updatePayload.estimatedProfit;
    delete updatePayload.profitMargin;

    const previousJobs = [...weldingJobs];
    // Update local state optimistically
    const updatedJobs = weldingJobs.map((job) =>
      job.id === jobId ? { ...job, ...updatePayload } : job
    );
    setWeldingJobs(updatedJobs);

    try {
      if (user && branchId) {
        const headers = await getAuthHeaders();
        await httpClient(`/welding/jobs/${jobId}`, {
          method: "PUT",
          headers,
          body: JSON.stringify(updatePayload),
        });
        toast({
          title: "Success",
          description: "Job updated successfully",
        });
        fetchWeldingJobs(currentPage);
      }
    } catch (err) {
      console.error("Failed to update job on server:", err);
      // Revert optimistic update
      setWeldingJobs(previousJobs);
      toast({
        title: "Error",
        description: "Failed to update job on server",
        variant: "destructive",
      });
    }
  };

  // const updateWeldingJob = async (
  //   jobId: string,
  //   updates: Partial<WeldingJob>
  // ) => {
  //   setWeldingJobs((prevJobs) =>
  //     prevJobs.map((job) => (job.id === jobId ? { ...job, ...updates } : job))
  //   );
  //   try {
  //     const headers = await getAuthHeaders();
  //     await httpClient(`/welding/jobs/${jobId}`, {
  //       method: "PUT",
  //       headers,
  //       body: JSON.stringify(updates),
  //     });
  //     toast({ title: "Success", description: "Job updated successfully" });
  //     fetchWeldingJobs(currentPage);
  //   } catch (err) {
  //     console.error("Failed to update job on server:", err);
  //     toast({
  //       title: "Error",
  //       description: "Failed to update job",
  //       variant: "destructive",
  //     });
  //     fetchWeldingJobs(currentPage); // Re-fetch to revert optimistic update
  //   }
  // };

  const deleteWeldingJob = async (jobId: string) => {
    try {
      const headers = await getAuthHeaders();
      await httpClient(`/welding/jobs/${jobId}`, {
        method: "DELETE",
        headers,
      });
      fetchWeldingJobs(currentPage);
      toast({ title: "Success", description: "Job deleted successfully" });
    } catch (err) {
      console.error("Failed to delete job on server:", err);
      toast({
        title: "Error",
        description: "Failed to delete job",
        variant: "destructive",
      });
    }
  };

  const getWeldingJobByIdNew = async (
    jobId: string
  ): Promise<WeldingJob | null> => {
    try {
      const headers = await getAuthHeaders();
      const response = await httpClient(`/welding/jobs/${jobId}`, {
        method: "GET",
        headers,
      });
      console.log("Fetched job details:", response);
      return response;
    } catch (err) {
      console.error("Failed to fetch job:", err);
      toast({
        title: "Error",
        description: "Failed to fetch job details",
        variant: "destructive",
      });
      return null;
    }
  };

  const getWeldingJobById = useCallback(
    (jobId: string) => {
      return weldingJobs.find((job) => job.id === jobId);
    },
    [weldingJobs]
  );

  const addMaterialStockItem = async (
    itemData: Omit<
      WeldingMaterialStock,
      "id" | "createdAt" | "updatedAt" | "isDeleted"
    >
  ) => {
    try {
      const headers = await getAuthHeaders();
      const response = await httpClient("/welding/stock/materials", {
        method: "POST",
        headers,
        body: JSON.stringify(itemData),
      });
      fetchMaterialStock();
      toast({ title: "Success", description: "Material added to stock" });
      return response;
    } catch (err) {
      console.error("Failed to create stock item on server:", err);
      toast({
        title: "Error",
        description: "Failed to add material to stock",
        variant: "destructive",
      });
      return null;
    }
  };

  const updateMaterialStockItem = async (
    itemId: string,
    updates: Partial<WeldingMaterialStock>
  ) => {
    setMaterialStock((prevStock) =>
      prevStock.map((item) =>
        item.id === itemId ? { ...item, ...updates } : item
      )
    );
    try {
      const headers = await getAuthHeaders();
      await httpClient(`/welding/stock/materials/${itemId}`, {
        method: "PUT",
        headers,
        body: JSON.stringify(updates),
      });
      toast({ title: "Success", description: "Material stock updated" });
      fetchMaterialStock();
    } catch (err) {
      console.error("Failed to update stock item on server:", err);
      toast({
        title: "Error",
        description: "Failed to update material stock",
        variant: "destructive",
      });
      fetchMaterialStock(); // Revert
    }
  };

  const deleteMaterialStockItem = async (itemId: string) => {
    try {
      const headers = await getAuthHeaders();
      await httpClient(`/welding/stock/materials/${itemId}`, {
        method: "DELETE",
        headers,
      });
      fetchMaterialStock();
      toast({ title: "Success", description: "Material removed from stock" });
    } catch (err) {
      console.error("Failed to delete stock item on server:", err);
      toast({
        title: "Error",
        description: "Failed to remove material from stock",
        variant: "destructive",
      });
    }
  };

  const getMaterialStockItemById = (itemId: string) => {
    return materialStock.find((item) => item.id === itemId);
  };

  const restockMaterialItem = async (
    stockId: string,
    quantity: number,
    supplierInfo?: string
  ) => {
    try {
      const headers = await getAuthHeaders();
      const response = await httpClient(
        `/welding/stock/materials/${stockId}/restock`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({ quantity, supplierInfo }),
        }
      );
      fetchMaterialStock();
      toast({ title: "Success", description: "Material restocked" });
      return true;
    } catch (err) {
      console.error("Failed to restock material on server:", err);
      toast({
        title: "Error",
        description: "Failed to restock material",
        variant: "destructive",
      });
      return false;
    }
  };

  const addMaterialToJob = async (
    jobId: string,
    materialData: Omit<WeldingMaterialNeeded, "id" | "createdAt" | "updatedAt">
  ) => {
    try {
      console.log("Adding material to job:", jobId, materialData);
      const headers = await getAuthHeaders();

      // Format the data according to server schema expectations
      const payload = {
        name: materialData.name,
        quantity: materialData.quantity,
        unit: materialData.unit,
        costPerUnit: materialData.costPerUnit,
        isCustom: materialData.isCustom,
        stockItemId: materialData.stockItemId,
        branchId: materialData.branchId,
        // Make sure weldingJobId is NOT included in the payload
        // as it's already in the URL path
      };

      // Remove undefined values to avoid validation issues
      const cleanPayload = Object.fromEntries(
        Object.entries(payload).filter(([_, value]) => value !== undefined)
      );

      const response = await httpClient(
        `/welding/materials/job/${jobId}/material`,
        {
          method: "POST",
          headers,
          body: JSON.stringify(cleanPayload),
        }
      );

      fetchWeldingJobs(currentPage);
      if (!materialData.isCustom) {
        fetchMaterialStock();
      }
      toast({ title: "Success", description: "Material added to job" });
      return response;
    } catch (err) {
      console.error("Failed to add material to job:", err);
      toast({
        title: "Error",
        description: (err as Error).message || "Failed to add material to job",
        variant: "destructive",
      });
      return null;
    }
  };

  const updateJobMaterial = async (
    materialId: string,
    updates: Partial<WeldingMaterialNeeded>
  ) => {
    // Optimistic update can be complex here due to stock changes.
    // A simple refetch is safer.
    try {
      const headers = await getAuthHeaders();
      await httpClient(`/welding/materials/material/${materialId}`, {
        method: "PUT",
        headers,
        body: JSON.stringify(updates),
      });
      fetchWeldingJobs(currentPage);
      fetchMaterialStock();
      toast({ title: "Success", description: "Job material updated" });
    } catch (err) {
      console.error("Failed to update job material:", err);
      toast({
        title: "Error",
        description: "Failed to update job material",
        variant: "destructive",
      });
    }
  };

  const removeMaterialFromJob = async (materialId: string) => {
    try {
      const headers = await getAuthHeaders();
      await httpClient(`/welding/materials/material/${materialId}`, {
        method: "DELETE",
        headers,
      });
      fetchWeldingJobs(currentPage);
      fetchMaterialStock();
      toast({ title: "Success", description: "Material removed from job" });
    } catch (err) {
      console.error("Failed to remove material from job:", err);
      toast({
        title: "Error",
        description: "Failed to remove material from job",
        variant: "destructive",
      });
    }
  };

  const getAvailableStock = async (branchId: string) => {
    try {
      const headers = await getAuthHeaders();
      const response = await httpClient(
        `/welding/materials/branch/${branchId}/available-stock`,
        { headers }
      );
      return parseAllNumbers(response || []);
    } catch (err) {
      console.error("Failed to fetch available stock:", err);
      toast({
        title: "Error",
        description: "Failed to fetch available stock",
        variant: "destructive",
      });
      return [];
    }
  };

  return (
    <WeldingContext.Provider
      value={{
        weldingJobs,
        loadingJobs,
        error,
        totalJobs,
        totalPages,
        currentPage,
        addWeldingJob,
        updateWeldingJob,
        deleteWeldingJob,
        getWeldingJobById,
        getWeldingJobByIdNew, //to be used
        fetchWeldingJobs,
        syncJobsWithBackend: fetchWeldingJobs,
        materialStock,
        loadingMaterialStock,
        errorMaterialStock,
        fetchMaterialStock,
        addMaterialStockItem,
        updateMaterialStockItem,
        deleteMaterialStockItem,
        getMaterialStockItemById,
        restockMaterialItem,
        syncMaterialStockWithBackend: fetchMaterialStock,
        addMaterialToJob,
        updateJobMaterial,
        removeMaterialFromJob,
        getAvailableStock,
        isSyncing,
        lastSyncTime,
        consumeMaterialFromStock: async () => false, // Placeholder
      }}
    >
      {children}
    </WeldingContext.Provider>
  );
};

export const useWelding = (): WeldingContextType => {
  const context = useContext(WeldingContext);
  if (!context) {
    throw new Error("useWelding must be used within a WeldingProvider");
  }
  return context;
};
