/**
 * @typedef {import('typeorm').MigrationInterface} MigrationInterface
 */

/**
 * @class
 * @implements {MigrationInterface}
 */
module.exports = class  $npmConfigName1760856819793 {
    name = ' $npmConfigName1760856819793'

    async up(queryRunner) {
        await queryRunner.query(`CREATE TABLE "temporary_welding_jobs" ("id" varchar PRIMARY KEY NOT NULL, "customerName" varchar NOT NULL, "customerContact" varchar NOT NULL, "customerLocation" varchar, "jobType" varchar NOT NULL, "description" text NOT NULL, "estimatedCost" decimal(12,2) NOT NULL, "requiredDeliveryDate" datetime NOT NULL, "status" text NOT NULL DEFAULT ('Pending'), "activeQuoteId" varchar, "activeInvoiceId" varchar, "assignedArtisans" text array, "deliveryConfirmed" boolean, "customerRating" smallint, "customerFeedback" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "branchId" varchar NOT NULL, "lastSyncAt" datetime, "isDeleted" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_a4b7431f4ea3700a2d4f7ac3c7e" FOREIGN KEY ("branchId") REFERENCES "branches" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_welding_jobs"("id", "customerName", "customerContact", "customerLocation", "jobType", "description", "estimatedCost", "requiredDeliveryDate", "status", "activeQuoteId", "activeInvoiceId", "assignedArtisans", "deliveryConfirmed", "customerRating", "customerFeedback", "createdAt", "updatedAt", "branchId", "lastSyncAt", "isDeleted") SELECT "id", "customerName", "customerContact", "customerLocation", "jobType", "description", "estimatedCost", "requiredDeliveryDate", "status", "activeQuoteId", "activeInvoiceId", "assignedArtisans", "deliveryConfirmed", "customerRating", "customerFeedback", "createdAt", "updatedAt", "branchId", "lastSyncAt", "isDeleted" FROM "welding_jobs"`);
        await queryRunner.query(`DROP TABLE "welding_jobs"`);
        await queryRunner.query(`ALTER TABLE "temporary_welding_jobs" RENAME TO "welding_jobs"`);
        await queryRunner.query(`CREATE TABLE "temporary_welding_jobs" ("id" varchar PRIMARY KEY NOT NULL, "customerName" varchar NOT NULL, "customerContact" varchar NOT NULL, "customerLocation" varchar, "jobType" varchar NOT NULL, "description" text NOT NULL, "estimatedCost" decimal(12,2) NOT NULL, "requiredDeliveryDate" datetime NOT NULL, "status" text NOT NULL DEFAULT ('Pending'), "activeQuoteId" varchar, "activeInvoiceId" varchar, "assignedArtisans" text array, "deliveryConfirmed" boolean, "customerRating" smallint, "customerFeedback" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "branchId" varchar NOT NULL, "lastSyncAt" datetime, "isDeleted" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_a4b7431f4ea3700a2d4f7ac3c7e" FOREIGN KEY ("branchId") REFERENCES "branches" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_welding_jobs"("id", "customerName", "customerContact", "customerLocation", "jobType", "description", "estimatedCost", "requiredDeliveryDate", "status", "activeQuoteId", "activeInvoiceId", "assignedArtisans", "deliveryConfirmed", "customerRating", "customerFeedback", "createdAt", "updatedAt", "branchId", "lastSyncAt", "isDeleted") SELECT "id", "customerName", "customerContact", "customerLocation", "jobType", "description", "estimatedCost", "requiredDeliveryDate", "status", "activeQuoteId", "activeInvoiceId", "assignedArtisans", "deliveryConfirmed", "customerRating", "customerFeedback", "createdAt", "updatedAt", "branchId", "lastSyncAt", "isDeleted" FROM "welding_jobs"`);
        await queryRunner.query(`DROP TABLE "welding_jobs"`);
        await queryRunner.query(`ALTER TABLE "temporary_welding_jobs" RENAME TO "welding_jobs"`);
    }

    async down(queryRunner) {
        await queryRunner.query(`ALTER TABLE "welding_jobs" RENAME TO "temporary_welding_jobs"`);
        await queryRunner.query(`CREATE TABLE "welding_jobs" ("id" varchar PRIMARY KEY NOT NULL, "customerName" varchar NOT NULL, "customerContact" varchar NOT NULL, "customerLocation" varchar, "jobType" varchar NOT NULL, "description" text NOT NULL, "estimatedCost" decimal(12,2) NOT NULL, "requiredDeliveryDate" datetime NOT NULL, "status" text NOT NULL DEFAULT ('Pending'), "activeQuoteId" varchar, "activeInvoiceId" varchar, "assignedArtisans" text array, "deliveryConfirmed" boolean, "customerRating" smallint, "customerFeedback" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "branchId" varchar NOT NULL, "lastSyncAt" datetime, "isDeleted" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_a4b7431f4ea3700a2d4f7ac3c7e" FOREIGN KEY ("branchId") REFERENCES "branches" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "welding_jobs"("id", "customerName", "customerContact", "customerLocation", "jobType", "description", "estimatedCost", "requiredDeliveryDate", "status", "activeQuoteId", "activeInvoiceId", "assignedArtisans", "deliveryConfirmed", "customerRating", "customerFeedback", "createdAt", "updatedAt", "branchId", "lastSyncAt", "isDeleted") SELECT "id", "customerName", "customerContact", "customerLocation", "jobType", "description", "estimatedCost", "requiredDeliveryDate", "status", "activeQuoteId", "activeInvoiceId", "assignedArtisans", "deliveryConfirmed", "customerRating", "customerFeedback", "createdAt", "updatedAt", "branchId", "lastSyncAt", "isDeleted" FROM "temporary_welding_jobs"`);
        await queryRunner.query(`DROP TABLE "temporary_welding_jobs"`);
        await queryRunner.query(`ALTER TABLE "welding_jobs" RENAME TO "temporary_welding_jobs"`);
        await queryRunner.query(`CREATE TABLE "welding_jobs" ("id" varchar PRIMARY KEY NOT NULL, "customerName" varchar NOT NULL, "customerContact" varchar NOT NULL, "customerLocation" varchar, "jobType" varchar NOT NULL, "description" text NOT NULL, "estimatedCost" decimal(12,2) NOT NULL, "requiredDeliveryDate" datetime NOT NULL, "status" text NOT NULL DEFAULT ('Pending'), "activeQuoteId" varchar, "activeInvoiceId" varchar, "assignedArtisans" text array, "deliveryConfirmed" boolean, "customerRating" smallint, "customerFeedback" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "branchId" varchar NOT NULL, "lastSyncAt" datetime, "isDeleted" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_a4b7431f4ea3700a2d4f7ac3c7e" FOREIGN KEY ("branchId") REFERENCES "branches" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "welding_jobs"("id", "customerName", "customerContact", "customerLocation", "jobType", "description", "estimatedCost", "requiredDeliveryDate", "status", "activeQuoteId", "activeInvoiceId", "assignedArtisans", "deliveryConfirmed", "customerRating", "customerFeedback", "createdAt", "updatedAt", "branchId", "lastSyncAt", "isDeleted") SELECT "id", "customerName", "customerContact", "customerLocation", "jobType", "description", "estimatedCost", "requiredDeliveryDate", "status", "activeQuoteId", "activeInvoiceId", "assignedArtisans", "deliveryConfirmed", "customerRating", "customerFeedback", "createdAt", "updatedAt", "branchId", "lastSyncAt", "isDeleted" FROM "temporary_welding_jobs"`);
        await queryRunner.query(`DROP TABLE "temporary_welding_jobs"`);
    }
}
