/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  ShoppingBag,
  UtensilsCrossed,
  Scissors,
  ShoppingCart,
  Pill,
  Car,
  Hammer,
  Coffee,
  Shirt,
  Fuel,
  Building2,
  Users,
  Leaf,
  Wrench,
  Store,
  Building,
  HeartPulse,
  Beer,
  ParkingCircle,
  CarFront,
} from "lucide-react";

export const businessCategories = [
  {
    title: "Wholesale",
    description: "For wholesale businesses.",
    icon: Building,
    features: ["Bulk Inventory", "Customer Management", "Sales Tracking"],
    type: "wholesale",
  },
  {
    title: "Supermarket",
    description: "For large-scale retail operations.",
    icon: ShoppingCart,
    features: ["Multi-department POS", "Bulk Inventory", "Promotions"],
    type: "supermarket",
  },
  {
    title: "Hardware",
    description: "For hardware and building supply stores.",
    icon: Hammer,
    features: [
      "Measurement-based selling",
      "Special Orders",
      "Vendor management",
    ],
    type: "hardware",
  },
  {
    title: "Pharmacy",
    description: "For pharmacies and drug stores.",
    icon: Pill,
    features: ["Prescription Management", "Drug Inventory", "Expiry Tracking"],
    type: "pharmacy",
  },
  {
    title: "Clinic",
    description: "For clinics and medical centers.",
    icon: HeartPulse,
    features: ["Patient Management", "Appointment Booking", "Billing"],
    type: "clinic",
  },
  {
    title: "Dept Store",
    description: "For department stores.",
    icon: Store,
    features: ["Inventory Management", "Sales Tracking", "Customer Management"],
    type: "dept_store",
  },
  {
    title: "Restaurant",
    description: "For cafes, bars, and restaurants.",
    icon: UtensilsCrossed,
    features: ["Table Management", "Order Tracking", "Kitchen Display"],
    type: "restaurant",
  },
  {
    title: "Bar",
    description: "For bars and pubs.",
    icon: Beer,
    features: ["Inventory Management", "Sales Tracking", "Tab Management"],
    type: "bar",
  },
  {
    title: "Agro Produce Store",
    description: "For agribusiness and farming.",
    icon: Leaf,
    features: ["Crop Management", "Livestock Tracking", "Supply Chain"],
    type: "agro",
  },
  {
    title: "Workshop/Professional Service",
    description: "For garages, repair shops, and artisans.",
    icon: Wrench,
    features: ["Job Cards", "Service Management", "Parts Inventory"],
    type: "workshop",
  },
  {
    title: "Retail",
    description: "For shops, boutiques, and general stores.",
    icon: ShoppingBag,
    features: ["Inventory Management", "Sales Tracking", "Customer Management"],
    type: "retail",
  },
  {
    title: "Salon",
    description: "For hair salons, spas, and beauty parlors.",
    icon: Scissors,
    features: ["Appointment Booking", "Stylist Management", "Service Packages"],
    type: "salon",
  },
  {
    title: "Washing Bay",
    description: "For car wash and vehicle cleaning services.",
    icon: Car,
    features: [
      "Service Management",
      "Worker Commissions",
      "Order Tracking",
      "Vehicle Type Pricing",
      "Commission Tracking",
    ],
    type: "washingbay",
  },
  {
    title: "Night Parking",
    description: "For overnight vehicle parking services.",
    icon: ParkingCircle,
    features: [
      "Slot Management",
      "Time-based Billing",
      "Vehicle Registration",
      "Security Features",
      "Night Shift Reports",
    ],
    type: "night_parking",
  },
  {
    title: "Washing Bay & Night Parking",
    description: "Combined car wash and overnight parking services.",
    icon: CarFront,
    features: [
      "Wash Service Management",
      "Parking Slot Allocation",
      "Combined Billing",
      "Vehicle Tracking",
      "Dual Service Packages",
      "Worker Commission for Both Services",
    ],
    type: "washingbay_nightparking",
  },
];
