import { DataSource } from "typeorm";
import {
  User,
  Branch,
  Item,
  Sale,
  SaleItem,
  Expense,
  StockMovement,
  Subscription,
  SyncLog,
  Business,
  SubscriptionPlan,
  Report,
  TransactionItem,
  Transaction,
  Customer,
  CreditEntry,
  CreditPayment,
  AgroProduct,
  StockShipment,
  AgroProductSaleItem,
  AgroSale,
  AgroCustomerDetails,
  WeldingJob,
  WeldingMaterialNeeded,
  WeldingMaterialStock,
  WeldingJobExpense,
  WeldingJobImage,
  WeldingQuote,
  WeldingInvoice,
  WeldingQuoteLineItem,
  WeldingInvoiceLineItem,
  WeldingInvoicePayment,
  AgroProductVariant
} from "../models";
const sslCert = (require("https").globalAgent.options.ca =
  require("ssl-root-cas").create());
require("dotenv").config();
console.log("Database URL:", process.env.DATABASE_URL);
export const AppDataSource = new DataSource({
  type: "postgres",
  url: process.env.DATABASE_URL,
  schema: process.env.DB_SCHEMA || "public",
  synchronize: process.env.NODE_ENV === "development",
  logging: process.env.NODE_ENV === "development",
  entities: [
    User,
    Branch,
    Item,
    Sale,
    SaleItem,
    Expense,
    StockMovement,
    Subscription,
    SyncLog,
    Business,
    Report,
    SubscriptionPlan,
    TransactionItem,
    Transaction,
    Customer,
    CreditEntry,
    CreditPayment,
    AgroProduct,
    StockShipment,
    AgroProductSaleItem,
    AgroSale,
    AgroCustomerDetails,
    WeldingJob,
    WeldingMaterialNeeded,
    WeldingMaterialStock,
    WeldingJobExpense,
    WeldingJobImage,
    WeldingQuote,
    WeldingInvoice,
    WeldingQuoteLineItem,
    WeldingInvoiceLineItem,
    WeldingInvoicePayment,
    AgroProductVariant,
  ],
  migrations: ["src/migrations/*.ts"],
  subscribers: [],
  // ssl: {
  //   ca: sslCert,
  //   rejectUnauthorized: false,
  // },
});
