import { DataSource } from "typeorm";
import {
  User,
  Branch,
  Item,
  Sale,
  SaleItem,
  Expense,
  StockMovement,
  Subscription,
  SyncLog,
  Business,
  SubscriptionPlan,
  Report,
  TransactionItem,
  Transaction,
  Customer,
  CreditEntry,
  CreditPayment,
  AgroProduct,
  StockShipment,
  AgroProductSaleItem,
  AgroSale,
  AgroCustomerDetails,
  WeldingJob,
  WeldingMaterialNeeded,
  WeldingMaterialStock,
  WeldingJobExpense,
  WeldingJobImage,
  WeldingQuote,
  WeldingInvoice,
  WeldingQuoteLineItem,
  WeldingInvoiceLineItem,
  WeldingInvoicePayment,
  AgroProductVariant
} from "../models";
export const AppDataSource = new DataSource({
  type: "sqlite",
  database: "db/simpos.sqlite",
  synchronize: true, // Should be true for development to auto-create schema
  logging: true, // Set to true to see SQL queries
  entities: [
    User,
    Branch,
    Item,
    Sale,
    SaleItem,
    Expense,
    StockMovement,
    Subscription,
    SyncLog,
    Business,
    Report,
    SubscriptionPlan,
    TransactionItem,
    Transaction,
    Customer,
    CreditEntry,
    CreditPayment,
    AgroProduct,
    StockShipment,
    AgroProductSaleItem,
    AgroSale,
    AgroCustomerDetails,
    WeldingJob,
    WeldingMaterialNeeded,
    WeldingMaterialStock,
    WeldingJobExpense,
    WeldingJobImage,
    WeldingQuote,
    WeldingInvoice,
    WeldingQuoteLineItem,
    WeldingInvoiceLineItem,
    WeldingInvoicePayment,
    AgroProductVariant,
  ],
  migrations: ["src/migrations/*.ts"],
  subscribers: [],
});
